### ISSUE TITLE
about application of efficient_transducer_loss

### ISSUE THREAD

**Issue by jinggaizi** [TeaPoly/Transducer-OptimizedLoss#1]
hi, 
can you use the improvement in your training. how can you process the output of join net: z, is reshape it and then free GPU memory?

**Comment by TeaPoly** [comment]
> hi,
> can you use the improvement in your training. how can you process the output of join net: z, is reshape it and then free GPU memory?

1.  can you use the improvement in your training. -> It's a method to save memory.
2. How to process the output of join net -> It's clear in Section 3.1. Efficient encoder and prediction output combination from IMPROVING RNN TRANSDUCER MODELING FOR END-TO-END SPEECH RECOGNITION (https://arxiv.org/pdf/1909.12415.pdf)

**Comment by jinggaizi** [comment]
谢谢回复，
英文不太好，我想表述的是目前很多开源的工具都是没有这方面的优化的，joint network的输出z依然是4维的，如果对z进行操作的话，原来的z还是会占显存，这个是需要释放掉还是说pytorch会动态释放；论文中的方法应该还是对z操作而不是直接对原始的batch进行操作吧

**Comment by TeaPoly** [comment]
> 谢谢回复，
> 英文不太好，我想表述的是目前很多开源的工具都是没有这方面的优化的，joint network的输出z依然是4维的，如果对z进行操作的话，原来的z还是会占显存，这个是需要释放掉还是说pytorch会动态释放；论文中的方法应该还是对z操作而不是直接对原始的batch进行操作吧

Combine Encoder and Prediction projection output, and process the sequences correctly at  later operations . Not using dynamic free joint network in pipeline. As stated in the article：
> Of course, we need to pass the sequence information like Tn, Un to any later operations so that they could process the sequences correctly based on such information.

You can refer to this part of the code:
https://github.com/TeaPoly/efficient_transducer_loss/blob/f3dc2bb8f54fed3b6c9852b63a81c1e890c821ca/EfficientCommbine.py#L16

**Comment by jinggaizi** [comment]
thanks very much

**Comment by jinggaizi** [comment]
if i sort the data and make closer lengths of a same batch , is the method effective? maybe  Function merging in section 3.2 is more effective

**Comment by TeaPoly** [comment]
> if i sort the data and make closer lengths of a same batch , is the method effective? maybe Function merging in section 3.2 is more effective

Yes, you are right.
